---
language: c
sudo: false

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

install:
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - .travis/install_stack.sh

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   stack --no-terminal build

after_success:
  - echo "YES"
