---
language: c
sudo: false

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

install:
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - git clone --depth=50 --branch=master https://github.com/bartavelle/confcheck-types.git ../confcheck-types/
 - git clone --depth=50 --branch=master https://github.com/bartavelle/confcheck-audittool.git ../confcheck-audittool/
 - .travis/install_stack.sh

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   ln -s stack.yaml.sample stack.yaml
   stack --no-terminal build

after_success:
  - echo "YES"
